#!/bin/bash
set -e

# install.sh - OpenTrusty Control Panel Installer
# Purpose: Installs the Control Panel static files and configures runtime environment.

COMPONENT="control-panel"
WEB_ROOT="/var/www/opentrusty-control-panel"

# 1. Root check
if [ "$EUID" -ne 0 ]; then
  echo "Error: This script must be run as root."
  exit 1
fi

echo "Installing OpenTrusty ${COMPONENT}..."

# 2. Create web directory
mkdir -p "${WEB_ROOT}"
echo "✓ Created web directory at ${WEB_ROOT}"

# 3. Copy static files
if [ -d "./dist" ]; then
  rm -rf "${WEB_ROOT}/dist"
  cp -r ./dist "${WEB_ROOT}/"
  echo "✓ Installed static files to ${WEB_ROOT}/dist"
else
  echo "Error: dist/ directory not found in current directory."
  exit 1
fi

# 4. Configure runtime environment
echo ""
echo "Configuring runtime environment..."

# Prompt for API URL if not set
if [ -z "$OPENTRUSTY_API_URL" ]; then
  read -p "Enter Admin Plane API URL (e.g., https://admin.yourdomain.com/api/v1): " OPENTRUSTY_API_URL
fi

if [ -z "$OPENTRUSTY_AUTH_URL" ]; then
  read -p "Enter Auth Plane URL (e.g., https://auth.yourdomain.com): " OPENTRUSTY_AUTH_URL
fi

# Write runtime config
cat > "${WEB_ROOT}/dist/config.js" << EOF
// Runtime configuration for OpenTrusty Control Panel
// Generated by install.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
window.__OPENTRUSTY_CONFIG__ = {
  API_BASE_URL: "${OPENTRUSTY_API_URL}",
  AUTH_BASE_URL: "${OPENTRUSTY_AUTH_URL}"
};
EOF

echo "✓ Created runtime configuration at ${WEB_ROOT}/dist/config.js"

# 5. Set permissions (for Caddy/nginx)
chown -R caddy:caddy "${WEB_ROOT}" 2>/dev/null || chown -R www-data:www-data "${WEB_ROOT}" 2>/dev/null || true
echo "✓ Set web server permissions"

echo ""
echo "Installation complete!"
echo ""
echo "Next steps:"
echo "1. Configure your web server (Caddy/Nginx) to serve ${WEB_ROOT}/dist"
echo "2. See Caddyfile.example for recommended configuration"
echo "3. Ensure the web server can reach the Admin and Auth Planes"
echo ""
